### ISSUE TITLE
Incorrect wording in chapter 10.3

### ISSUE THREAD

**Issue by eliasazarian** [cognitive-engineering-lab/rust-book#102]
URL to the section(s) of the book with this problem:
https://rust-book.cs.brown.edu/ch10-03-lifetime-syntax.html
Description of the problem:
The lifetime parameter declaration after impl and its use after the type name are required, but we’re not required to annotate the lifetime of the reference to self because of the first elision rule.
Suggested fix:
The lifetime parameter declaration after impl and its use after the type name are required, but we’re not required to annotate the lifetime of the reference to self because of the third elision rule.

**Comment by willcrichton** [comment]
This would not be a case of the third elision rule, which describes the lifetimes out of output references, not input references.
