### ISSUE TITLE
Sometimes text highlighting extends to the bottom of the page when reloading.

### ISSUE THREAD

**Issue by DemonQilin** [cognitive-engineering-lab/rust-book#114]
- I have searched open and closed issues and pull requests for duplicates, using these search terms:
  - highlight
  - invalid
  - broken
- I have checked the latest `main` branch to see if this has already been fixed, in this file:
  - [utils.ts](https://github.com/cognitive-engineering-lab/rust-book/blob/main/js-extensions/packages/feedback/lib/utils.ts)

## Description of the problem:
Sometimes when highlighting text and reloading the page, the target text is no longer highlighted but instead all text following it is highlighted to the end.

I don't have a clear individual replication path, but I copied [my highlights](https://gist.github.com/DemonQilin/639d8fb3ad78446ba9165b1014bbdb93) from the `localStorage` to Chrome, Firefox and Edge and in all of them the same error happened.

By having the [highlights](https://gist.github.com/DemonQilin/639d8fb3ad78446ba9165b1014bbdb93) and visiting the following sections:
- [https://rust-book.cs.brown.edu/ch09-02-recoverable-errors-with-result.html](https://rust-book.cs.brown.edu/ch09-02-recoverable-errors-with-result.html)
- [https://rust-book.cs.brown.edu/ch10-02-traits.html](https://rust-book.cs.brown.edu/ch10-02-traits.html)
- [https://rust-book.cs.brown.edu/ch10-03-lifetime-syntax.html](https://rust-book.cs.brown.edu/ch10-03-lifetime-syntax.html)
- [https://rust-book.cs.brown.edu/ch13-01-closures.html](https://rust-book.cs.brown.edu/ch13-01-closures.html)
- [https://rust-book.cs.brown.edu/ch14-02-publishing-to-crates-io.html](https://rust-book.cs.brown.edu/ch14-02-publishing-to-crates-io.html)

The pages look like this:
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/100786328/542ad5a2-7d9c-40b2-80c2-c6b4a7b47f35)

And the following error appears in the console:
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/100786328/9c2e5baf-61ce-42a1-b8fc-65f8c14939f7)

## Suggested fix:
I have identified that the error occurs within the `highlightIsValid` function of the [utils.ts](https://github.com/cognitive-engineering-lab/rust-book/blob/main/js-extensions/packages/feedback/lib/utils.ts) file on line 67, where the `innerHTML` of the first element of the `dom_nodes` array is readed but **this array is empty** because the validation of line 64 uses the statement `if (!dom_nodes) return false;` which only validates that it is not falsy but not its length.

Therefore it should be corrected by replacing this validation with:
```ts
export const highlightIsValid = (highlighter: Highlighter, highlight: HighlightSource) => {
  /*other code*/

  // if highlight has no DOM node, filter
  if (!dom_node?.length) return false;
};
```

**Comment by willcrichton** [comment]
This will be fixed in #117. Thanks for finding the issue!
