### ISSUE TITLE
Highlighting text does not work

### ISSUE THREAD

**Issue by Zeroji** [cognitive-engineering-lab/rust-book#12]
- [ ] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem: <https://rust-book.cs.brown.edu/> (first highlight test)

Description of the problem: Highlighting doesn't work

Whenever I press "Submit" in the highlight input box, with or without having entered text, nothing happens (box doesn't even close) and the following appears in my console:
![image](https://user-images.githubusercontent.com/15339858/215316208-d91cba01-5a0f-4328-84f6-0d27799784b1.png)

Obfuscated JS probably isn't that useful, but here is where my debugger thinks the issue is:
![image](https://user-images.githubusercontent.com/15339858/215316270-dcd195a1-e9d8-4e3c-ad68-36d7dedc7c56.png)

System details:
OS: Linux Mint XFCE 21.1
Browser: Firefox 108.0.2

Let me know if more information is required :)

**Comment by vipulrawat** [comment]
It (still) happen if you triple-click to select the entire paragraph
