### ISSUE TITLE
Listing 15-25. The code defines and imports List enum simultaneously 

### ISSUE THREAD

**Issue by i-kudryavtsev** [cognitive-engineering-lab/rust-book#129]
- I have searched open and closed issues and pull requests for duplicates, using these search terms:
  -
  -
  -
- I have checked the latest `main` branch to see if this has already been fixed, in this file:
  -

URL to the section(s) of the book with this problem:

Description of the problem:

Suggested fix:

**Comment by willcrichton** [comment]
This is intended behavior, I think. It's importing the branches of the enum so they can be referred to concisely (i.e., `Cons` instead of `List::Cons`).
