### ISSUE TITLE
Example of unsafe as a solution for ownership error is not valid

### ISSUE THREAD

**Issue by cagatay-y** [cognitive-engineering-lab/rust-book#133]
- I have searched open and closed issues and pull requests for duplicates, using these search terms:
  - split_first_mut
  - unsafe
- I have checked the latest `main` branch to see if this has already been fixed, in this file:
  - https://github.com/cognitive-engineering-lab/rust-book/blob/1694d3da3825e104ebb823e740b1a668cf938333/src/ch04-03-fixing-ownership-errors.md?plain=1#L433

URL to the section(s) of the book with this problem: https://rust-book.cs.brown.edu/ch04-03-fixing-ownership-errors.html?search=#fixing-a-safe-program-mutating-different-array-elements

Description of the problem: The book explains that split_first_mut works using unsafe, which as far as I understand [is not the case](https://github.com/rust-lang/rust/blob/091bb74e7ed00e806f617d52f3159d4843460191/library/core/src/slice/mod.rs#L238-L240) (since 2020 based on [git blame](https://github.com/rust-lang/rust/blame/091bb74e7ed00e806f617d52f3159d4843460191/library/core/src/slice/mod.rs#L239)).

Suggested fix: This explanation cannot simply be removed, since it is used as a segue to explain the occasional necessity of unsafe blocks. I don't know what would be better example to make the case for unsafe blocks in this case.

**Comment by willcrichton** [comment]
Ah great catch! I had originally written this using `split_at_mut` (which does actually use unsafe), and then thought "hmm well it would be simpler to just use `split_first_mut`. But of course, that's a special case that reduces to pattern matching :| I will revert the section to use `split_at_mut`.
