### ISSUE TITLE
In-Browser IDE's Compatibility with Safari

### ISSUE THREAD

**Issue by mckzm** [cognitive-engineering-lab/rust-book#146]
https://github.com/cognitive-engineering-lab/rust-book/blob/ff61a875d55967a10272b7cfc89b8fd7e54af5b6/src/ch06-04-inventory.md?plain=1#L30C160-L30C160

The above states:

`**PLATFORM COMPATIBILITY:** the in-browser IDE does not work on touch-screens. The in-browser IDE has only been tested to work on Google Chrome 109 and Firefox 107. It definitely does not work in Safari.`

As best as I could see the in-browser IDE worked just fine for me on Safari 17.1.2/macos Sonoma 14.1.2 (M1 Max chip), across all Ownership Inventory tests: all tooltips seem to appear without issue.

**Comment by willcrichton** [comment]
Oh yeah it seems to be working for me too. I'll clarify in the book.

**Comment by mckzm** [comment]
Thanks Will.

Just a nit: there's a typo in your commit, which has "verisons" instead of "versions". I submitted <https://github.com/cognitive-engineering-lab/rust-book/pull/153> to fix it.
