### ISSUE TITLE
mutating a variable’s type does not give an error

### ISSUE THREAD

**Issue by block0xhash** [cognitive-engineering-lab/rust-book#170]
Hi
It says here https://rust-book.cs.brown.edu/ch03-01-variables-and-mutability.html  that:

if we try to use `mut` for a variable that is shadowed you will get an error:
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/ddd42518-70ce-48b0-b9b5-24b0e3ebeb72)

however I got a warning instead and the code runs:

![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/3eea116c-d3c2-4ca9-9453-d45838ff3db1)

```
~/rustbook/variables$ cargo --version
cargo 1.76.0 (c84b36747 2024-01-18)
~/rustbook/variables$ rustc --version
rustc 1.76.0 (07dca489a 2024-02-04
```

**Comment by willcrichton** [comment]
The book's snippet is not shadowing `spaces`, but rather re-assigning to it. Note that there is no `let` keyword on the second line.

**Comment by block0xhash** [comment]
Thanks Will. I get it now 
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/fac11f6f-64c3-4dfe-94f4-cb75aba1573b)
