### ISSUE TITLE
Possible to use /*  */ for block comments

### ISSUE THREAD

**Issue by block0xhash** [cognitive-engineering-lab/rust-book#171]
I suppose the book should mention that one can use `/*      */` for comments that extend beyond a single line instead of using `//` on every line

https://rust-book.cs.brown.edu/ch03-04-comments.html
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/3f51e3c2-ea49-48f5-afd6-410e6187a7ab)

![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/72ce4a19-18d4-4202-9ced-64965ca6b920)

**Comment by willcrichton** [comment]
Good idea, I'll add this to the section.
