### ISSUE TITLE
string slice vs string literal

### ISSUE THREAD

**Issue by block0xhash** [cognitive-engineering-lab/rust-book#175]
In https://rust-book.cs.brown.edu/ch08-02-strings.html I am finding the interchangable use of  string slice and string literal to be a tricky

`let data = "initial contents";  // is referred to as a string literal` 

further down we are saying:

 `let s2 = "bar"; // is referred to as a string slice`

below we are creating a string from a string literal using the` to_string()` method which is available to a string literals because they implement the `Display` trait. 

So in the code below variable `data `is indeed a string literal because we are calling `data.to_string()`
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/47210522-596d-45cc-a054-22e8073b7f35)

however `s2`  below is referred  to  as a string slice, which is used after appending its contents to a string ?
![image](https://github.com/cognitive-engineering-lab/rust-book/assets/16897613/1392fc69-d946-4d06-b0e4-9d5bc71d11f1)

is `s2 `not a string literal  just like `data` ?

are string literals and string slices the same thing ?

**Comment by twhentschel** [comment]
According to [this stackoverflow answer](https://stackoverflow.com/a/24159933/22218756), a string literal is just a `&'static str`, so it's a string slice but with a static lifetime.

note: I'm still learning so I may be wrong.

**Comment by willcrichton** [comment]
@twhentschel's answer is correct. To be more precise, all string literals are string slices, but not all string slices are string literals. For example:

```
let s = String::from("foo");
let s_ref: &str = &s;
```

In this case, the expression `&s` is a string slice, but not a string literal.
