### ISSUE TITLE
Question: why does s lose all permissions at the end of the program?

### ISSUE THREAD

**Issue by antoniogamizbadger** [cognitive-engineering-lab/rust-book#178]
Hi, I'm reading this [section](https://rust-book.cs.brown.edu/ch04-04-slices.html) and I have found the following code:

<img width="786" alt="image" src="https://github.com/cognitive-engineering-lab/rust-book/assets/73933988/32aec93d-8b28-4a9f-9861-e4f18e426786">

```rust
fn main() {
    let mut s = String::from("hello");
    let hello: &str = &s[0..5];
    println!("{hello}");
    s.push_str(" world"); # here s loses all permissions
}
```

Not sure why that happens. Maybe is because is the end of the block where `s` is defined? If I try:

```rust
fn main() {
    let mut s = String::from("hello");
    let hello: &str = &s[0..5];
    println!("{hello}");
    s.push_str(" world");
    s.push_str(" world"); 
}
```

Then it works fine, which makes sense. What also makes sense, is that it fails if I try:

```rust
fn main() {
    let mut s = String::from("hello");
    let hello: &str = &s[0..5];
    println!("{hello}");
    s.push_str(" world");
    println!("{hello}");
}
```

Thanks and sorry if it's a trivial question! The book is amazing so thanks for creating it!

**Comment by twhentschel** [comment]
I'm still learning too, but I think your observation

> Maybe is because is the end of the block where `s` is defined?

is spot on. `s` is no longer used in that block so it loses all permissions. See the explanation to the first example in [4.2 References Change Permissions on Paths](https://rust-book.cs.brown.edu/ch04-02-references-and-borrowing.html#references-change-permissions-on-paths).

**Comment by block0xhash** [comment]
https://rust-book.cs.brown.edu/ch04-02-references-and-borrowing.html#permissions-are-returned-at-the-end-of-a-references-lifetime

**Comment by willcrichton** [comment]
Similar question to #177 and cognitive-engineering-lab/aquascope#85. Please do carefully read the example at the bottom of [`"References Change Permissions on Paths"`](https://rust-book.cs.brown.edu/ch04-02-references-and-borrowing.html#references-change-permissions-on-paths).
