### ISSUE TITLE
Text highlighting color in dark mode.

### ISSUE THREAD

**Issue by peterspbr** [cognitive-engineering-lab/rust-book#18]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:

Description of the problem:
When highlighting some piece of text while in dark themes (i'm actually using the navy theme) it uses a bright yellow color that makes the text hard to read.
I'm using Firefox while using the book.

Suggested fix:
Use some color for highlighting in dark themes that gives more contrast between the text and the highlighting itself.

**Comment by willcrichton** [comment]
Thanks for the report. I'll pick a more appropriate color for dark themes and add this in the next release.

**Comment by peterspbr** [comment]
Thanks!
