### ISSUE TITLE
Plans to merge original book updates since Feb 2023?

### ISSUE THREAD

**Issue by kriswilk** [cognitive-engineering-lab/rust-book#191]
I'm a newcomer to Rust and was about to dive into this experimental book to take advantage of the quizzes. I also see that Chapter 4 has been changed considerably. However, this fork still indicates that it's based on "Rust 1.67.1 (released 2023-02-09)" and is currently 271 commits behind the source repo.

I'm sure that the fundamentals of the language haven't changed. But as a newcomer to Rust it's important to me that my reference is up-to-date, from the basics to the details.

Are there plans to merge the upstream changes?

**Comment by willcrichton** [comment]
Yes, I will eventually get around to merging the upstream changes. I haven't looked at them yet, but I expect they are all minor (they were last time I did an upstream merge). You are safe to read the current version of the experimental book.
