### ISSUE TITLE
wrong quiz

### ISSUE THREAD

**Issue by Neutron3529** [cognitive-engineering-lab/rust-book#192]
URL to the section(s) of the book with this problem:

https://rust-book.cs.brown.edu/ch01-02-hello-world.html

Description of the problem:

> Question 1
> Every executable Rust program must contain a function with the name:

The answer is not available, since the following code compiles (at least with `RUSTC_BOOTSTRAP=1 rustc - `):
```
#![feature(start)]#[start]fn start(a:isize, _b:*const *const u8) -> isize{a}
```

Suggested fix:

Delete the question, since no answer is available.

**Comment by willcrichton** [comment]
It is the correct answer for people who have just read to Section 1.2 of the book. If someone understands Rust at your level, then they don't need to answer this question :-)
