### ISSUE TITLE
Comma missing in Chapter 3.2 sentence

### ISSUE THREAD

**Issue by thebrownone** [cognitive-engineering-lab/rust-book#20]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:
https://rust-book.cs.brown.edu/ch03-02-data-types.html

Description of the problem:
In the sentence "Every value in Rust is of a certain data type, which tells Rust what kind of data is being specified so it knows how to work with that data. We’ll look at two data type subsets: scalar and compound.", there is a missing comma after "data is being specified". I think it will make the sentence more readable. 

Suggested fix:
Add a comma after "data is being specified" and before "so it knows how to work with that data".

Thanks. I am just learning Rust and Git at the same time.

**Comment by willcrichton** [comment]
Hi, thanks for the report. I think it's grammatically correct to omit the comma because "it knows how to work with that data" is a dependent clause, but I will consider a better phrasing.
