### ISSUE TITLE
Answers no longer saved to or restored from localStorage

### ISSUE THREAD

**Issue by wodny** [cognitive-engineering-lab/rust-book#213]
- I have searched open and closed issues and pull requests for duplicates, using these search terms:
  - localStorage
  - local storage
  - lost answers

URL to the section(s) of the book with this problem:
global problem

Description of the problem:
Answers are no longer saved to or restored from localStorage. It worked yesterday but today every time I refresh the page quiz pieces all look unanswered. Purging localStorage and answering again did not change anything.

Consent status, session ID and theme are still saved to localStorage.

**Comment by willcrichton** [comment]
Thanks for the report. I will fix this ASAP.

**Comment by wodny** [comment]
Works again. Thank you.

**Comment by mkohlhaas** [comment]
Problem emerges again! ;-)
