### ISSUE TITLE
404  rust-book.cs.brown.edu

### ISSUE THREAD

**Issue by adiSuper94** [cognitive-engineering-lab/rust-book#22]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:

Description of the problem:
I not sure if this is an intermittent issue or some network issue. But the [https://rust-book.cs.brown.edu/](https://rust-book.cs.brown.edu/) shows 404.
Suggested fix:

**Comment by willcrichton** [comment]
Thanks for reporting the issue! I had misconfigured a CI action, but that is fixed, and the link is live again.
