### ISSUE TITLE
Continue outside a loop while handling invalid input

### ISSUE THREAD

**Issue by thi-marques** [cognitive-engineering-lab/rust-book#32]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:
https://rust-book.cs.brown.edu/ch02-00-guessing-game-tutorial.html#handling-invalid-input

Description of the problem:

The following code:
```rust
let mut guess = String::new();

// --snip--

let guess: u32 = match guess.trim().parse() {
    Ok(num) => num,
    Err(_) => continue,
};
```

Throws the error below on `rustc 1.67.1 (d5a82bbd2 2023-02-07)`
```
`continue` outside of a loop
cannot `continue` outside of a loop (rustc E0268)
─────────────────────────────────────────────────────────────────
https://doc.rust-lang.org/error-index.html#E0268
```

**Comment by willcrichton** [comment]
Hi @thi-marques, you cannot always copy code verbatim from the snippets you see. That snippet in particular has hidden lines. You can click the eye button in the top-right to see the hidden lines. You can also click the copy button in the top-right to copy all the code, including the hidden lines.

**Comment by thi-marques** [comment]
Hi, @willcrichton. Thank you for the expanation.
