### ISSUE TITLE
Confusion of "type" and "value'

### ISSUE THREAD

**Issue by seishun** [cognitive-engineering-lab/rust-book#71]
- [x] I have checked the latest `main` branch to see if this has already been fixed
- [x] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem:
https://rust-book.cs.brown.edu/ch19-04-advanced-types.html#the-never-type-that-never-returns

Description of the problem:

>Rust has a special type named ! that’s known in type theory lingo as the empty type because it has no values.

Later it says:

>As you might have guessed, continue has a ! value. That is, when Rust computes the type of guess, it looks at both match arms, the former with a value of u32 and the latter with a ! value.

>Here, the loop never ends, so ! is the value of the expression.

How can `!` be the value of something if it's a type that has no values?

Suggested fix:

Replace "value" with "type" where appropriate.

**Comment by willcrichton** [comment]
Fixed this in 780b7c9372a3581d08f4eeed814685b3dc753c2a.
