### ISSUE TITLE
Wrong function in code example in section 4.5

### ISSUE THREAD

**Issue by andreqts** [cognitive-engineering-lab/rust-book#82]
- [X] I have checked the latest `main` branch to see if this has already been fixed
- [X] I have searched existing issues and pull requests for duplicates

URL to the section(s) of the book with this problem: https://rust-book.cs.brown.edu/ch04-05-ownership-recap.html

Description of the problem:

In the 4th code example, the function make_document is called, but it is not defined in the example nor in previous ones.

Suggested fix:
Replace with new_document, function that is defined in previous code block, and seem to work fine, and it seems that were the original intention.

**Comment by willcrichton** [comment]
Thanks, fixed in #83.
