### ISSUE TITLE
Question: testing read permission of a path

### ISSUE THREAD

**Issue by musjj** [cognitive-engineering-lab/rust-book#98]
I was reading your version of The Rust Book, and I find the read/write/own permission concept pretty interesting. But I have a question, and since I don't know where else to ask about this, I'm posting this here.
How do you test if a path is readable?

For example, you can test if a path has own and write permissions like this:

```rust
let mut s = String::from("hello world");
s = String::from("changed"); // `s` has write permission
let s_1 = s; // `s` has ownership permission
```

But how do you test if a path has read permission?

**Comment by willcrichton** [comment]
The simplest test of whether you have read permissions on a path `p` is that you can construct an immutable reference `&p`. For example, if you have a string `s`, then you have read permissions if you can call `s.len()`.

This is a good question though-- I'll think about how we can make this clearer in the book

**Comment by musjj** [comment]
Thanks, that clarifies my doubt!
