### ISSUE TITLE
Warn about the resource usage of the Ownership Inventory more clearly

### ISSUE THREAD

**Issue by musjj** [cognitive-engineering-lab/rust-book#99]
The article already warns that:

> Each instance of the IDE appears to take around ~300 MB.

But I don't think this warning is dire enough as to how much memory it's going to actually consume. This is how much memory it ended up consuming in the quiz result view (on Firefox).

![2023-06-27T17:41:04](https://github.com/cognitive-engineering-lab/rust-book/assets/72612857/f23b53cc-e842-4693-81b9-eb0eda9b46e1)
It completely froze my 4GB RAM potato when I did the quiz. I recently upgraded to 16GB and even then it struggled (it started swapping even though I'm not running anything but the browser).

**Comment by willcrichton** [comment]
12GB! Oh no. I'll up the warning... and see if I can figure out why it's causing such resource usage.
